# -*- coding: utf-8 -*-
"""_fractures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nal3j2APAjosgUTVg5ifJggo1EijeLWr
"""

# -------- Imports --------
import numpy as np
import scipy.sparse as sp
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from _utility import *



# =====================
# MATERIAL PROPERTIES
# =====================

c_p_base = 6000  # P-wave velocity (m/s)
c_s_base = 3500  # S-wave velocity (m/s)
rho_base = 2700  # Base density (granite) (kg/m³)

# Fracture properties (water-filled fractures)
rho_fracture = 1000  # 1000 is Water density (kg/m³)
K_water = 2.2e9  # Water bulk modulus (Pa)
mu_fracture = 1e-6  # Very small shear modulus for numerical stability
lambda_fracture = K_water  # Bulk modulus for λ

# Compute base material Lamé parameters
mu_base = rho_base * c_s_base ** 2
lambda_base = rho_base * c_p_base ** 2 - 2 * mu_base




def get_grid_parameters():

    xmin,ymin,zmin = -1,-1,-1
    xmax,ymax,zmax = 1,1,1
    Nx, Ny, Nz = 5, 5, 5
    dx, dy, dz = (xmax-xmin)/(Nx-1), (ymax-ymin)/(Ny-1), (zmax-zmin)/(Nz-1)

    return xmin,ymin,zmin,xmax,ymax,zmax,Nx,Ny,Nz,dx,dy,dz

def get_grid_size(Nx,Ny,Nz):

    # Calculate staggered grid sizes for 3D elastic
    N_main = Nx * Ny * Nz
    N_vx = (Nx-1) * Ny * Nz
    N_vy = Nx * (Ny-1) * Nz
    N_vz = Nx * Ny * (Nz-1)
    N_sxy = (Nx-1) * (Ny-1) * Nz
    N_sxz = (Nx-1) * Ny * (Nz-1)
    N_syz = Nx * (Ny-1) * (Nz-1)
    N_vel = N_vx + N_vy + N_vz
    N_stress = 3*N_main + N_sxy + N_sxz + N_syz
    psi_len = N_vel + N_stress  # Total state vector size for 3D elastic

    return N_main,N_vx,N_vy,N_vz,N_sxy,N_sxz,N_syz,N_vel,N_stress,psi_len


    
#Define function to check parameters
def print_material_parameters():

    print(f"\nFracture properties (water-filled):")
    print(f"  λ_fracture = {lambda_fracture:.2e} Pa")
    print(f"  μ_fracture = {mu_fracture:.2e} Pa")
    print(f"  ρ_fracture = {rho_fracture:.1f} kg/m³")
    print(f"  Expected c_p = {np.sqrt((lambda_fracture + 2 * mu_fracture) / rho_fracture):.1f} m/s")

def no_fractures(Nx,Ny,Nz,dx,dy,dz):
    rho_model = np.full((Nz, Ny, Nx), rho_base)
    S_base = create_compliance_matrix_from_velocities(c_p_base, c_s_base, rho_base)
    return rho_model,S_base
    

def one_horizontal_fracture(Nx,Ny,Nz,dx,dy,dz,fracture_thickness=0):

    S_base = create_compliance_matrix_from_velocities(c_p_base, c_s_base, rho_base)

# ============================================================================
# CREATE DENSITY MODEL WITH FRACTURE
# ============================================================================
    rho_model = np.full((Nz, Ny, Nx), rho_base)
    fracture_mask = np.zeros((Nz, Ny, Nx), dtype=bool)

    # One horizontal fracture plane
    fracture1_z = Nz // 2  # Horizontal plane (constant z)

    #Don't let the fractures extend into the top or bottom fourth of the domain

    frac_high_ind_x = 3*Nx//4
    frac_low_ind_x = Nx//4
    frac_high_ind_y = 3*Ny//4
    frac_low_ind_y = Ny//4

    print(f"\nAdding horizontal fracture planes:")
    print(f"  Fracture: Horizontal plane at z-index {fracture1_z}")

    fracture_cells = 0
    for i in range(Nz):
        for j in range(Ny):
            for k in range(Nx):
                is_fracture = (abs(i - fracture1_z) <= fracture_thickness and j>=frac_low_ind_y and j<frac_high_ind_y
                               and k>=frac_low_ind_x and k<frac_high_ind_x)
                if is_fracture:
                    fracture_mask[i, j, k] = True
                    fracture_cells += 1
                    rho_model[i, j, k] = rho_fracture

    print(
        f"  Total fracture cells: {fracture_cells} out of {Nx * Ny * Nz} ({100 * fracture_cells / (Nx * Ny * Nz):.1f}%)")

    # Clip density to reasonable bounds
    rho_model = np.clip(rho_model, 1.0, 3000)

    print(f"\nDensity Model Statistics:")
    print(f"  Min: {np.min(rho_model):.1f} kg/m³, Max: {np.max(rho_model):.1f} kg/m³")
    print(f"  Mean: {np.mean(rho_model):.1f} kg/m³, Std: {np.std(rho_model):.1f} kg/m³")

    # ============================================================================
    # CREATE SPATIALLY VARYING COMPLIANCE MATRIX
    # ============================================================================

    S_model = np.zeros((6, 6, Nz, Ny, Nx))

    for i in range(Nz):
        for j in range(Ny):
            for k in range(Nx):
                if fracture_mask[i, j, k]:
                    S_model[:, :, i, j, k] = create_compliance_matrix_isotropic(
                        lambda_fracture, mu_fracture
                    )
                else:
                    S_model[:, :, i, j, k] = S_base

    S = S_model

    return rho_model,S







def one_vertical_fracture(Nx,Ny,Nz,dx,dy,dz,fracture_thickness=0):

    S_base = create_compliance_matrix_from_velocities(c_p_base, c_s_base, rho_base)

# ============================================================================
# CREATE DENSITY MODEL WITH FRACTURE
# ============================================================================
    rho_model = np.full((Nz, Ny, Nx), rho_base)
    fracture_mask = np.zeros((Nz, Ny, Nx), dtype=bool)

    # One vertical fracture plane
    fracture1_x = Nx // 2  # Vertical plane (constant x)

    #Don't let the fractures extend into the top or bottom fourth of the domain

    frac_high_ind_z = 3*Nz//4
    frac_low_ind_z = Nz//4
    frac_high_ind_y = 3*Ny//4
    frac_low_ind_y = Ny//4

    print(f"\nAdding vertical fracture plane:")
    print(f"  Fracture: Vertical plane at x-index {fracture1_x}")

    fracture_cells = 0
    for i in range(Nz):
        for j in range(Ny):
            for k in range(Nx):
                is_fracture = (abs(k - fracture1_x) <= fracture_thickness and j>=frac_low_ind_y and j<frac_high_ind_y
                               and i>=frac_low_ind_z and k<frac_high_ind_z)
                if is_fracture:
                    fracture_mask[i, j, k] = True
                    fracture_cells += 1
                    rho_model[i, j, k] = rho_fracture

    print(
        f"  Total fracture cells: {fracture_cells} out of {Nx * Ny * Nz} ({100 * fracture_cells / (Nx * Ny * Nz):.1f}%)")

    # Clip density to reasonable bounds
    rho_model = np.clip(rho_model, 1.0, 3000)

    print(f"\nDensity Model Statistics:")
    print(f"  Min: {np.min(rho_model):.1f} kg/m³, Max: {np.max(rho_model):.1f} kg/m³")
    print(f"  Mean: {np.mean(rho_model):.1f} kg/m³, Std: {np.std(rho_model):.1f} kg/m³")

    # ============================================================================
    # CREATE SPATIALLY VARYING COMPLIANCE MATRIX
    # ============================================================================

    S_model = np.zeros((6, 6, Nz, Ny, Nx))

    for i in range(Nz):
        for j in range(Ny):
            for k in range(Nx):
                if fracture_mask[i, j, k]:
                    S_model[:, :, i, j, k] = create_compliance_matrix_isotropic(
                        lambda_fracture, mu_fracture
                    )
                else:
                    S_model[:, :, i, j, k] = S_base

    S = S_model

    return rho_model,S


def two_perpendicular_fractures(Nx,Ny,Nz,dx,dy,dz,fracture_thickness=0):

    S_base = create_compliance_matrix_from_velocities(c_p_base, c_s_base, rho_base)

# ============================================================================
# CREATE DENSITY MODEL WITH FRACTURE
# ============================================================================
    rho_model = np.full((Nz, Ny, Nx), rho_base)
    fracture_mask = np.zeros((Nz, Ny, Nx), dtype=bool)

    # One vertical fracture plane
    fracture1_x = Nx // 2  # Vertical plane (constant x)
    fracture2_z = Nz // 2  # Horizontal plane (constant z)
    #Don't let the fractures extend into the top or bottom fourth of the domain

    frac_high_ind_x = 3*Nx//4
    frac_low_ind_x = Nx//4
    frac_high_ind_z = 3*Nz//4
    frac_low_ind_z = Nz//4
    frac_high_ind_y = 3*Ny//4
    frac_low_ind_y = Ny//4

    print(f"\nAdding perpendicular fracture planes:")
    print(f"  Fracture: Vertical plane at x-index {fracture1_x}")
    print(f"  Fracture: Horizontal plane at z-index {fracture2_z}")

    fracture_cells = 0
    for i in range(Nz):
        for j in range(Ny):
            for k in range(Nx):
                is_fracture = ((abs(k - fracture1_x) <= fracture_thickness and j>=frac_low_ind_y and j<frac_high_ind_y
                               and i>=frac_low_ind_z and k<frac_high_ind_z) or (abs(i - fracture2_z) <= fracture_thickness 
                                and j>=frac_low_ind_y and j<frac_high_ind_y and k>=frac_low_ind_x and k<frac_high_ind_x))
                if is_fracture:
                    fracture_mask[i, j, k] = True
                    fracture_cells += 1
                    rho_model[i, j, k] = rho_fracture

    print(
        f"  Total fracture cells: {fracture_cells} out of {Nx * Ny * Nz} ({100 * fracture_cells / (Nx * Ny * Nz):.1f}%)")

    # Clip density to reasonable bounds
    rho_model = np.clip(rho_model, 1.0, 3000)

    print(f"\nDensity Model Statistics:")
    print(f"  Min: {np.min(rho_model):.1f} kg/m³, Max: {np.max(rho_model):.1f} kg/m³")
    print(f"  Mean: {np.mean(rho_model):.1f} kg/m³, Std: {np.std(rho_model):.1f} kg/m³")

    # ============================================================================
    # CREATE SPATIALLY VARYING COMPLIANCE MATRIX
    # ============================================================================

    S_model = np.zeros((6, 6, Nz, Ny, Nx))

    for i in range(Nz):
        for j in range(Ny):
            for k in range(Nx):
                if fracture_mask[i, j, k]:
                    S_model[:, :, i, j, k] = create_compliance_matrix_isotropic(
                        lambda_fracture, mu_fracture
                    )
                else:
                    S_model[:, :, i, j, k] = S_base

    S = S_model

    return rho_model,S